DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS task_categories;

CREATE TABLE task_categories (
    category_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name           VARCHAR2(100) NOT NULL,
    category_description    VARCHAR2(500)
);

CREATE TABLE tasks (
    task_id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_name           VARCHAR2(100) NOT NULL,
    task_description    VARCHAR2(500),
    deadline            TIMESTAMP NOT NULL,
    category_id         NUMBER NOT NULL,
    author              VARCHAR_IGNORECASE(50) NOT NULL
);
ALTER TABLE tasks ADD CONSTRAINT task_categories_fk FOREIGN KEY (category_id) REFERENCES task_categories (category_id);
ALTER TABLE tasks ADD CONSTRAINT users_fk FOREIGN KEY (author) REFERENCES users (username);