name: Main CI workflow
on: push
jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build
      run: ./gradlew build
    - name: Test
      run: ./gradlew test
